[package]
name = "simdintersection-sys"
version = "0.1.0"
authors = ["Andrew Pendleton <andrew@mapbox.com>"]

[dependencies]
cpp = "0.5"

[build-dependencies]
cpp_build = "0.5"

[lib]
name = "simdintersection_sys"
path = "lib.rs"