[package]
name = "streamvbyte-sys"
version = "0.1.0"
authors = ["Andrew Pendleton <andrew@mapbox.com>"]

[dependencies]

[build-dependencies]
cc = "1.0"

[lib]
name = "streamvbyte_sys"
path = "lib.rs"